// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_FTxNQVuMsH3XMCz3MpuSTxytVwNdWMQ',
    appId: '1:946196020149:web:e8bc91f3a4ea07342e77fc',
    messagingSenderId: '946196020149',
    projectId: 'todo-42-43613',
    authDomain: 'todo-42-43613.firebaseapp.com',
    storageBucket: 'todo-42-43613.appspot.com',
    measurementId: 'G-C1G1KS42ND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvrCb-7IJf_np3khWnIbjDQF-1PW4m2C8',
    appId: '1:946196020149:android:c6e13b7dd7fd4c1d2e77fc',
    messagingSenderId: '946196020149',
    projectId: 'todo-42-43613',
    storageBucket: 'todo-42-43613.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7buOHMeEIg8RSrzUTCzlZb_P8qSALbQo',
    appId: '1:946196020149:ios:9b66cd53c27c642e2e77fc',
    messagingSenderId: '946196020149',
    projectId: 'todo-42-43613',
    storageBucket: 'todo-42-43613.appspot.com',
    iosClientId: '946196020149-l9n0g40hmn6eeklsu0u5hhgc5mtfg07p.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7buOHMeEIg8RSrzUTCzlZb_P8qSALbQo',
    appId: '1:946196020149:ios:9b66cd53c27c642e2e77fc',
    messagingSenderId: '946196020149',
    projectId: 'todo-42-43613',
    storageBucket: 'todo-42-43613.appspot.com',
    iosClientId: '946196020149-l9n0g40hmn6eeklsu0u5hhgc5mtfg07p.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapps',
  );
}
